import {
  getMeProcedure,
  updateMeProcedure,
  uploadAvatarProcedure,
  deleteAvatarProcedure,
  listMySessionsProcedure,
  revokeMySessionProcedure,
  revokeOtherSessionsProcedure,
} from "@/server/orpc/routes/users"
import {
  listCompaniesProcedure,
  getCompanyByIdProcedure,
  createCompanyProcedure,
  listCompanyMembersProcedure,
  inviteCompanyMemberProcedure,
  removeCompanyMemberProcedure,
  updateCompanyProcedure,
  approveCompanyProcedure,
  rejectCompanyProcedure,
  suspendCompanyProcedure,
  reactivateCompanyProcedure,
  uploadCompanyLogoProcedure,
  getCompanyTrustIndexProcedure,
  listCompanyTrustIndicesProcedure,
  submitCompanyQualityFeedbackProcedure,
  submitCompanyReportProcedure,
  listCompanyReportsProcedure,
  resolveCompanyReportProcedure,
} from "@/server/orpc/routes/companies"
import { listSkillTagsProcedure, listSkillTagsPrioritizedProcedure } from "@/server/orpc/routes/skills"
import {
  getStudentProfileProcedure,
  getPublicStudentProfileProcedure,
  upsertStudentProfileProcedure,
  upsertStudentProfileDetailsProcedure,
} from "@/server/orpc/routes/students"
import {
  getOfferByIdProcedure,
  listOffersByCompanyProcedure,
  listSavedOffersProcedure,
  checkOfferSavedProcedure,
  saveOfferProcedure,
  unsaveOfferProcedure,
  createOfferProcedure,
  updateOfferProcedure,
  deleteOfferProcedure,
  updateOfferStatusProcedure,
  parseSearchQueryProcedure,
  generateOfferDraftProcedure,
  improveOfferDescriptionProcedure,
  suggestOfferSkillsProcedure,
} from "@/server/orpc/routes/offers"
import {
  searchOffersProcedure,
  checkApplicationProcedure,
  applyToOfferProcedure,
  listStudentApplicationsProcedure,
  withdrawApplicationProcedure,
  listByOfferProcedure,
  companyAcceptProcedure,
  companyRefuseProcedure,
  updatePipelineStageProcedure,
  getTimelineProcedure,
  generateCoverLetterProcedure,
} from "@/server/orpc/routes/applications"
import {
  listPendingProcedure,
  validateProcedure,
  rejectProcedure,
  deptHeadListPendingProcedure,
  deptHeadValidateProcedure,
  deptHeadRejectProcedure,
  generateValidationSummaryProcedure,
} from "@/server/orpc/routes/placements"
import {
  listDepartmentsProcedure,
  createDepartmentProcedure,
  updateDepartmentProcedure,
  assignDepartmentHeadProcedure,
  unassignDepartmentHeadProcedure,
  deleteDepartmentProcedure,
  bulkCreateDepartmentsProcedure,
  syncDepartmentSkillsProcedure,
  getDepartmentSkillsProcedure,
} from "@/server/orpc/routes/departments"
import {
  downloadCompanyDocumentProcedure,
  generateAgreementProcedure,
  generateCompanyCertificateProcedure,
  listCompanyDocumentsProcedure,
  listStudentDocumentsProcedure,
  downloadDocumentProcedure,
  verifyDocumentProcedure,
} from "@/server/orpc/routes/documents"
import {
  listNotificationsProcedure,
  getNotificationPreferencesProcedure,
  updateNotificationPreferencesProcedure,
  markAllNotificationsReadProcedure,
  markNotificationReadProcedure,
} from "@/server/orpc/routes/notifications"
import {
  getAdminStatsProcedure,
  getUniversityDashboardStatsProcedure,
} from "@/server/orpc/routes/stats"
import {
  appendAssistantMessageProcedure,
  createAssistantConversationProcedure,
  deleteAssistantConversationProcedure,
  getAssistantConversationProcedure,
  listAssistantModelsProcedure,
  listAssistantConversationsProcedure,
  listAssistantMessagesProcedure,
  updateAssistantConversationModelProcedure,
  updateAssistantConversationTitleProcedure,
} from "@/server/orpc/routes/assistant"
import {
  captureReadinessSnapshotProcedure,
  getReadinessHistoryProcedure,
  getScoreProcedure,
  getSkillGapProcedure,
} from "@/server/orpc/routes/matching"
import {
  confirmInterviewSlotProcedure,
  listInterviewsForCompanyProcedure,
  listInterviewsForStudentProcedure,
  proposeInterviewSlotsProcedure,
} from "@/server/orpc/routes/interviews"
import {
  listUsersProcedure,
  createUserProcedure,
  setRoleProcedure,
  banUserProcedure,
  unbanUserProcedure,
  removeUserProcedure,
  setPasswordProcedure,
  updateUserProcedure,
  listUserSessionsProcedure,
  revokeSessionProcedure,
  revokeAllSessionsProcedure,
} from "@/server/orpc/routes/admin-users"
import {
  listUniversitiesProcedure,
  getUniversityByIdProcedure,
  createUniversityProcedure,
  updateUniversityProcedure,
  deleteUniversityProcedure,
  approveUniversityProcedure,
  rejectUniversityProcedure,
} from "@/server/orpc/routes/universities"
import {
  listMessageThreadsByCompanyProcedure,
  listMessageThreadsByStudentProcedure,
  listThreadMessagesProcedure,
  markThreadReadProcedure,
  sendOfferMessageByCompanyProcedure,
  sendOfferMessageByStudentProcedure,
} from "@/server/orpc/routes/messages"
import {
  createStudentExperienceProcedure,
  createStudentProjectProcedure,
  deleteStudentExperienceProcedure,
  deleteStudentProjectProcedure,
  deleteStudentResumeProcedure,
  getStudentCvProcedure,
  updateStudentExperienceProcedure,
  updateStudentProjectProcedure,
  uploadStudentResumeProcedure,
} from "@/server/orpc/routes/student-cv"

export const appRouter = {
  users: {
    getMe: getMeProcedure,
    updateMe: updateMeProcedure,
    uploadAvatar: uploadAvatarProcedure,
    deleteAvatar: deleteAvatarProcedure,
    listMySessions: listMySessionsProcedure,
    revokeMySession: revokeMySessionProcedure,
    revokeOtherSessions: revokeOtherSessionsProcedure,
  },
  companies: {
    list: listCompaniesProcedure,
    getById: getCompanyByIdProcedure,
    create: createCompanyProcedure,
    listMembers: listCompanyMembersProcedure,
    inviteMember: inviteCompanyMemberProcedure,
    removeMember: removeCompanyMemberProcedure,
    update: updateCompanyProcedure,
    approve: approveCompanyProcedure,
    reject: rejectCompanyProcedure,
    suspend: suspendCompanyProcedure,
    reactivate: reactivateCompanyProcedure,
    uploadLogo: uploadCompanyLogoProcedure,
    getTrustIndex: getCompanyTrustIndexProcedure,
    listTrustIndices: listCompanyTrustIndicesProcedure,
    submitQualityFeedback: submitCompanyQualityFeedbackProcedure,
    submitReport: submitCompanyReportProcedure,
    listReports: listCompanyReportsProcedure,
    resolveReport: resolveCompanyReportProcedure,
  },
  skills: {
    list: listSkillTagsProcedure,
    listPrioritized: listSkillTagsPrioritizedProcedure,
  },
  students: {
    getProfile: getStudentProfileProcedure,
    getPublicProfile: getPublicStudentProfileProcedure,
    upsertProfile: upsertStudentProfileProcedure,
    upsertProfileDetails: upsertStudentProfileDetailsProcedure,
  },
  offers: {
    getById: getOfferByIdProcedure,
    listByCompany: listOffersByCompanyProcedure,
    listSaved: listSavedOffersProcedure,
    checkSaved: checkOfferSavedProcedure,
    save: saveOfferProcedure,
    unsave: unsaveOfferProcedure,
    create: createOfferProcedure,
    update: updateOfferProcedure,
    delete: deleteOfferProcedure,
    updateStatus: updateOfferStatusProcedure,
    search: searchOffersProcedure,
    parseSearchQuery: parseSearchQueryProcedure,
    generateDraft: generateOfferDraftProcedure,
    improveDescription: improveOfferDescriptionProcedure,
    suggestSkills: suggestOfferSkillsProcedure,
  },
  applications: {
    checkApplication: checkApplicationProcedure,
    apply: applyToOfferProcedure,
    listByStudent: listStudentApplicationsProcedure,
    withdraw: withdrawApplicationProcedure,
    listByOffer: listByOfferProcedure,
    companyAccept: companyAcceptProcedure,
    companyRefuse: companyRefuseProcedure,
    updatePipelineStage: updatePipelineStageProcedure,
    getTimeline: getTimelineProcedure,
    generateCoverLetter: generateCoverLetterProcedure,
  },
  matching: {
    getScore: getScoreProcedure,
    getSkillGap: getSkillGapProcedure,
    getReadinessHistory: getReadinessHistoryProcedure,
    captureReadinessSnapshot: captureReadinessSnapshotProcedure,
  },
  placements: {
    listPending: listPendingProcedure,
    validate: validateProcedure,
    reject: rejectProcedure,
    generateValidationSummary: generateValidationSummaryProcedure,
  },
  deptHead: {
    listPending: deptHeadListPendingProcedure,
    validate: deptHeadValidateProcedure,
    reject: deptHeadRejectProcedure,
  },
  departments: {
    list: listDepartmentsProcedure,
    create: createDepartmentProcedure,
    update: updateDepartmentProcedure,
    assignHead: assignDepartmentHeadProcedure,
    unassignHead: unassignDepartmentHeadProcedure,
    delete: deleteDepartmentProcedure,
    bulkCreateWithHeads: bulkCreateDepartmentsProcedure,
    syncSkills: syncDepartmentSkillsProcedure,
    getSkills: getDepartmentSkillsProcedure,
  },
  documents: {
    generateAgreement: generateAgreementProcedure,
    listByStudent: listStudentDocumentsProcedure,
    download: downloadDocumentProcedure,
    listByCompany: listCompanyDocumentsProcedure,
    generateCertificateByCompany: generateCompanyCertificateProcedure,
    downloadByCompany: downloadCompanyDocumentProcedure,
    verify: verifyDocumentProcedure,
  },
  notifications: {
    list: listNotificationsProcedure,
    getPreferences: getNotificationPreferencesProcedure,
    updatePreferences: updateNotificationPreferencesProcedure,
    markRead: markNotificationReadProcedure,
    markAllRead: markAllNotificationsReadProcedure,
  },
  interviews: {
    listForCompany: listInterviewsForCompanyProcedure,
    listForStudent: listInterviewsForStudentProcedure,
    proposeSlots: proposeInterviewSlotsProcedure,
    confirmSlot: confirmInterviewSlotProcedure,
  },
  messages: {
    listByCompany: listMessageThreadsByCompanyProcedure,
    listByStudent: listMessageThreadsByStudentProcedure,
    listThreadMessages: listThreadMessagesProcedure,
    sendByCompany: sendOfferMessageByCompanyProcedure,
    sendByStudent: sendOfferMessageByStudentProcedure,
    markThreadRead: markThreadReadProcedure,
  },
  studentCv: {
    get: getStudentCvProcedure,
    createExperience: createStudentExperienceProcedure,
    updateExperience: updateStudentExperienceProcedure,
    deleteExperience: deleteStudentExperienceProcedure,
    createProject: createStudentProjectProcedure,
    updateProject: updateStudentProjectProcedure,
    deleteProject: deleteStudentProjectProcedure,
    uploadResume: uploadStudentResumeProcedure,
    deleteResume: deleteStudentResumeProcedure,
  },
  stats: {
    getAdminStats: getAdminStatsProcedure,
    getUniversityDashboardStats: getUniversityDashboardStatsProcedure,
  },
  adminUsers: {
    list: listUsersProcedure,
    create: createUserProcedure,
    setRole: setRoleProcedure,
    ban: banUserProcedure,
    unban: unbanUserProcedure,
    remove: removeUserProcedure,
    setPassword: setPasswordProcedure,
    update: updateUserProcedure,
    listSessions: listUserSessionsProcedure,
    revokeSession: revokeSessionProcedure,
    revokeAllSessions: revokeAllSessionsProcedure,
  },
  universities: {
    list: listUniversitiesProcedure,
    getById: getUniversityByIdProcedure,
    create: createUniversityProcedure,
    update: updateUniversityProcedure,
    delete: deleteUniversityProcedure,
    approve: approveUniversityProcedure,
    reject: rejectUniversityProcedure,
  },
  assistant: {
    listModels: listAssistantModelsProcedure,
    listConversations: listAssistantConversationsProcedure,
    createConversation: createAssistantConversationProcedure,
    deleteConversation: deleteAssistantConversationProcedure,
    getConversation: getAssistantConversationProcedure,
    listMessages: listAssistantMessagesProcedure,
    updateConversationModel: updateAssistantConversationModelProcedure,
    updateConversationTitle: updateAssistantConversationTitleProcedure,
    appendMessage: appendAssistantMessageProcedure,
  },
}

export type AppRouter = typeof appRouter
