import { Button, Heading, Section, Text } from "@react-email/components"

import EmailLayout from "@/server/email/templates/EmailLayout"

interface CertificateGeneratedEmailProps {
  studentName: string
  companyName: string
  offerTitle: string
  internshipType: string
  startDate: string
  endDate: string
  verificationCode: string
  documentsUrl: string
}

export default function CertificateGeneratedEmail({
  studentName,
  companyName,
  offerTitle,
  internshipType,
  startDate,
  endDate,
  verificationCode,
  documentsUrl,
}: CertificateGeneratedEmailProps) {
  return (
    <EmailLayout title="Your Internship Certificate Is Ready - Stag">
      <Section className="bg-card my-6 rounded-lg px-6 py-12 text-center">
        <Heading as="h1" className="text-primary mb-2 text-2xl font-bold">
          Stag
        </Heading>
        <Heading as="h2" className="text-foreground mb-4 text-3xl font-bold">
          Your internship certificate is ready
        </Heading>
        <Text className="text-mutedForeground mb-3 text-base">
          Hi <strong>{studentName}</strong>, your internship certificate has
          been generated by your company.
        </Text>
        <Section className="bg-background my-4 rounded-md border border-border px-4 py-4 text-start">
          <Text className="text-mutedForeground mb-1 text-xs font-semibold uppercase tracking-wider">
            Placement Summary
          </Text>
          <Text className="text-foreground text-sm mb-1">
            <strong>Company:</strong> {companyName}
          </Text>
          <Text className="text-foreground text-sm mb-1">
            <strong>Offer:</strong> {offerTitle}
          </Text>
          <Text className="text-foreground text-sm mb-1">
            <strong>Type:</strong> {internshipType}
          </Text>
          <Text className="text-foreground text-sm mb-1">
            <strong>Start:</strong> {startDate}
          </Text>
          <Text className="text-foreground text-sm">
            <strong>End:</strong> {endDate}
          </Text>
        </Section>
        <Text className="text-mutedForeground mb-6 text-sm">
          Verification code: <strong>{verificationCode}</strong>
        </Text>
        <Button
          className="bg-primary rounded-lg px-6 py-3 font-semibold text-white"
          href={documentsUrl}
        >
          View My Documents
        </Button>
      </Section>
    </EmailLayout>
  )
}
